sudo: false
language: python
cache: pip

services:
- docker

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy-5.3.1

addons:
  ssh_known_hosts:
  - localhost

matrix:
  allow_failures:
  - python: pypy
  - python: pypy-5.3.1

before_install:
- docker pull sjourdan/alpine-sshd
- pip install -U setuptools wheel

install:
- pip install .[dev,test]

script:
- green

after_script:
- codecov

before_deploy:
- python setup.py check -rms

deploy:
  provider: pypi
  user: althonos
  password:
    secure: q82KcRQ+Zm0MuZApN9ac1gT0kI7MrIwurcf1Vo82dk+GcMw7l6BSoWWNir106YfT9SEy4/BsstuMBr3qrIWfS2Tgja8FT2va9mU1gmROwhVgb6A94VadP9HsxaDX1vOlJt28Q0KLKndJlk4je563Pd7iij8R1LKyZVOkHiphCvG4czlV/dKMT6vluF3Wc4Py7rJld8Q00CHx5apsDjbxM48NYNIvMtgz1kZ3EAWbHQOLpIHCGFrmSnr/2sm0vKxomYt+RLWXuMuxGQEaRMXKvAefWGJNKR5R8jJlYcPBi5Zgf8YDnBoQrjYcij8rjXxYdU/weEywCS3Q6wIFrH/bA3WheyztGre24B6m4nfOiqhXhfHFu7zBC6CfXZcWLqOX0UKIfL/+CYDN+n9ziXC5GDz7oxxZTch2pQwOM5iDJKfcW6995U5fhyccOB9FJq5iJexE2AG3eeA39IQLZHyGQl3x9hyO3DyCBHuCzs6jrY0q//vFGHlXDKff7VGB4XvRGME/8XixTRCJozMVqpDVyzdxf7v5hEsmHCRkMtgCsiHCebjAPh9rAF5I5NetcT4UERv84o09Q+/gDpkHdxt+3UlbvMAV6bMFV8rVqxopH8dFuI2AJKW4f2I2X4qN8J/fIdhc3T8q8V9L/+dTHTbI+Jph5NoWbSo8c0vxysWdxuQ=
  on:
    tags: true
    repo: althonos/fs.sshfs
    python: 3.6
  distributions: sdist bdist_wheel
  server: https://upload.pypi.org/legacy/
  skip_upload_docs: true

notifications:
  email:
  - althonosdev@gmail.com
